# SPDX-License-Identifier: MIT
# Copyright (c) 2024, Kolya

name: Bug Report
description: Use this template to report bugs in the project.
labels: bug
body:
  - type: markdown
    attributes:
      value: "Please describe the bug you encountered."
  - type: input
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: "e.g. open app, click on button"
